openapi: 3.0.0
info:
  title: "FastAPI Backend"
  description: "API for managing files, multi-agents, and WebSocket communication."
  version: "1.0.0"

servers:
  - url: "http://localhost:9090"
    description: "Local development server"

paths:
  /:
    get:
      summary: "Render index page"
      description: "Returns the index page using Jinja2 templates."
      responses:
        "200":
          description: "HTML page rendered successfully"

  /files/:
    get:
      summary: "List all files"
      description: "Returns a list of available files in the outputs directory."
      responses:
        "200":
          description: "List of files"
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: string

  /files/{filename}:
    get:
      summary: "Download a file"
      description: "Fetches and downloads a file from the outputs directory."
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "File retrieved successfully"
          content:
            application/octet-stream: {}

        "404":
          description: "File not found"

    delete:
      summary: "Delete a file"
      description: "Deletes a file from the outputs directory."
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "File deleted successfully"
        "404":
          description: "File not found"

  /upload/:
    post:
      summary: "Upload a file"
      description: "Uploads a file and saves it in the outputs directory."
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: "File uploaded successfully"
        "400":
          description: "Invalid file upload request"

  /api/multi_agents:
    post:
      summary: "Execute multi-agent tasks"
      description: "Runs multiple agents for processing."
      responses:
        "200":
          description: "Multi-agent execution completed successfully"
        "500":
          description: "Internal server error"

  /ws:
    get:
      summary: "WebSocket Connection"
      description: "Establishes a WebSocket connection for real-time updates."
      responses:
        "101":
          description: "WebSocket connection established"
        "400":
          description: "Bad request"
