openapi: 3.0.0
info:
  title: Multi-Agent Research System API
  version: '1.0.0'
  description: |
    This OpenAPI specification defines the REST API for research execution, 
    file management, and other functionalities.

servers:
  - url: http://localhost:8000/api/v1
    description: Local server

paths:
  /:
    get:
      summary: Render the index page
      operationId: readRoot
      parameters:
        - name: request
          in: query
          required: false
          description: The HTTP request object.
      responses:
        '200':
          description: Successfully rendered index page
          content:
            text/html:
              schema:
                type: string

  /files/{filename}:
    get:
      summary: Retrieve a specific file
      operationId: getFile
      parameters:
        - name: filename
          in: path
          required: true
          description: Name of the file to retrieve
          schema:
            type: string
      responses:
        '200':
          description: File retrieved successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: File not found

  /files/:
    get:
      summary: List all available files
      operationId: listFiles
      responses:
        '200':
          description: Successfully retrieved list of files
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: string
                    example: ["file1.txt", "report.pdf"]

  /multi_agents:
    post:
      summary: Execute multi-agent research
      operationId: runMultiAgents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                  example: "Summarize research papers"
                report_type:
                  type: string
                  example: "detailed"
                agent:
                  type: string
                  example: "gpt-4"
      responses:
        '200':
          description: Multi-agent execution started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "started"

  /upload/:
    post:
      summary: Upload a file
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  filename:
                    type: string
                    example: "uploaded_file.txt"

  /files/{filename}:
    delete:
      summary: Delete a specific file
      operationId: deleteFile
      parameters:
        - name: filename
          in: path
          required: true
          description: Name of the file to delete
          schema:
            type: string
      responses:
        '200':
          description: File deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "File deleted"
        '404':
          description: File not found
